### ISSUE TITLE
Detected device not installing

### ISSUE THREAD

**Issue by noohi** [zauan/hassio-prana#1]
Hi,

thank you for the component.
Having an issue where it detects the device via Bluetooth proxy, but cannot add it.
Screenshots attached, I presume type the name on the first prompt or manually a MAC, and tried checkbox and no checkbox on the second prompt, nothing.

[Step 1 screenshot](https://drive.google.com/file/d/1xD8ojTI0jSoLSQiFUJ2PTvZyjugiKqWm/view?usp=sharing)
[Step 2 screenshot](https://drive.google.com/file/d/1-vNK3eTzIdq1HAdBXRyU0UuwstLRo8VX/view?usp=sharing)

Added in configuration:
logger:
  default: error
  logs:
    custom_components.prana: debug

But no info in the log at all. Except the generic "We found a custom integration prana which has not been tested by Home Assistant."

Any tips to debug this if yours works fine on HASS 2023.6.3?
I can also do some mild coding if needed, I see you mentioned not having the time and that's appreciated.

Thanks.

**Comment by zauan** [comment]
Hi there,

Unfortunately, i cannot maintain this repository as i am not a python programmer. I've just made a commit that should resolve adding the devices from discovery. Please check and let me know

**Comment by noohi** [comment]
Thank you, much better, now it detects and adds.
Functionality has some issues, haven't yet debugged in details, but this is already plenty.
